annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.21.0
description: Chart for the nginx server
engine: gotpl
home: https://github.com/bboule/charts/tree/master/bitnami/nginx
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
keywords:
  - nginx
  - http
  - web
  - www
  - reverse proxy
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: nginx
sources:
  - https://github.com/bitnami/bitnami-docker-nginx
  - http://www.nginx.org
version: 9.3.2
